name = "kaisar"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "vip.kopralstore.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.vip.kopralstore.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.vip.kopralstore.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.vip.kopralstore.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vip.kopralstore.my.id", custom_domain = true },
  { pattern = "support.zoom.us.vip.kopralstore.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.vip.kopralstore.my.id", custom_domain = true },

  { pattern = "free.kopralstore.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.free.kopralstore.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.free.kopralstore.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.free.kopralstore.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.free.kopralstore.my.id", custom_domain = true },
  { pattern = "support.zoom.us.free.kopralstore.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.free.kopralstore.my.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "c598b08770654155ac40773492c1f0d5"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "01978f2e-2db2-7852-a35b-f73eacc651d7"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/link.html"
