name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "vpn.krikkrik.tech", custom_domain = true },
  { pattern = "bakrie.ac.id.vpn.krikkrik.tech", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "895c737ee9db4cf2947ded0c264582d6"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]

UUID = "f282b878-8711-45a1-8c69-5564172123c1"

MAIN_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/converter.html"
CHECKER_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/checker.html"
