name = "seadanya"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "donghua.kaisaronline.web.id", custom_domain = true },
  { pattern = "ava.gameka.naver.com.donghua.kaisaronline.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.donghua.kaisaronline.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.donghua.kaisaronline.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.donghua.kaisaronline.web.id", custom_domain = true },
  { pattern = "support.zoom.us.donghua.kaisaronline.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.donghua.kaisaronline.web.id", custom_domain = true },

  { pattern = "jebret.kaisaronline.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.jebret.kaisaronline.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.jebret.kaisaronline.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.jebret.kaisaronline.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.jebret.kaisaronline.web.id", custom_domain = true },
  { pattern = "support.zoom.us.jebret.kaisaronline.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.jebret.kaisaronline.web.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "99f6323e5990426e8f8433d6bd9b8c9b"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/KopralProject/vpn-cf/refs/heads/master/web/link.html"
